#!/usr/bin/env python

import sys
from subprocess import call
import argparse

def runContainer(containerName, rootPassword):
    call('docker run --name ' + containerName + ' -p 3306:3306 -e MYSQL_ROOT_PASSWORD="' + rootPassword + '" -d mysql', shell=True)
    return

def main():

    parser = argparse.ArgumentParser(
    description="Creates a new MySQL container using the mysql image",
    prog="dmysql-server")

    parser.add_argument("containerName", help="The name of the mysql container to create")
    parser.add_argument("rootPassword", help="The root password to define when creating the container")

    args = parser.parse_args()

    runContainer(containerName=args.containerName, rootPassword=args.rootPassword)
    return

# Execute main
main()